[project]
name = "python_samples-monorepo"
version = "0.1.0"
description = "A Monorepo for all my Python projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.sources]
utilities = { workspace = true }
sample = { workspace = true }
sample_core = { workspace = true }
simple_storage = { workspace = true }
simple_worker = { workspace = true }


[tool.uv.workspace]
members = ["packages/*", "apps/*"]

[dependency-groups]
dev = [
    "pre-commit>=3.8.0",
    "ipykernel>=6.29.5",
    "pytest>=8.3.4",
    "ruff>=0.9.5",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-asyncio>=0.25.3",
    "mypy>=1.15.0",
    "mypy-extensions>=1.0.0",

    # These are added as dev dependencies becuase they should be available
    #  when developing the project.
    "utilities",
    "sample",
    "sample_core",
    "simple_storage",
    "simple_worker",
]
